"""
Pydantic schemas defining the structured outputs generated by each GTM agent.
"""
from typing import Any, Optional
from pydantic import BaseModel, Field


# ─── Brand Agent Schema ────────────────────────────────────────────────────────
class BrandGTMOutput(BaseModel):
    event_name: str = Field(description="MEMORABLE, creative, name of the hackathon aligned with the theme.")
    tagline: str = Field(description="Punchy, under 10 words tagline describing the hackathon.")
    tone_adjectives: list[str] = Field(description="Exactly 3 adjectives defining the brand voice.")
    color_primary: str = Field(description="Primary hex code color choice matching the theme (e.g. #3d5eff).")
    color_secondary: str = Field(description="Secondary hex code color choice (e.g. #d946ef).")
    color_names: list[str] = Field(description="Names of the selected primary and secondary colors (e.g. ['Electric Indigo', 'Neon Magenta']).")
    persona_text: str = Field(description="Target audience profile paragraph (150 words max).")


# ─── Structure Agent Schema ─────────────────────────────────────────────────────
class TimelineMilestone(BaseModel):
    title: str
    description: str
    duration: str


class ScheduleTimetableItem(BaseModel):
    time: str = Field(description="Hour-by-hour slot (e.g. '09:00 AM', '10:30 AM')")
    activity: str = Field(description="Activity name")
    duration_mins: int = Field(description="Duration in minutes")
    type: str = Field(description="Category of activity: 'session', 'break', 'activity', or 'ceremony'")


class TeamRolesItem(BaseModel):
    role: str
    responsibilities: list[str]


class JudgingCriteriaItem(BaseModel):
    name: str
    weight: int = Field(description="Percentage weight (e.g. 20)")
    description: str


class PrizeStructureItem(BaseModel):
    position: str
    prize: str
    details: str


class StructureGTMOutput(BaseModel):
    timeline: dict[str, list[TimelineMilestone]] = Field(description="Timeline containing lists of milestones categorized under keys: 'pre_event', 'event_day', and 'post_event'")
    schedule: list[ScheduleTimetableItem] = Field(description="Hour-by-hour schedule list")
    team_roles: list[TeamRolesItem] = Field(description="Core team roles needed to run the hackathon")
    venue_checklist: list[str] = Field(description="Checklist of facilities/platforms needed")
    judging_criteria: list[JudgingCriteriaItem] = Field(description="5 parameters with percentage weights totaling 100")
    prize_structure: list[PrizeStructureItem] = Field(description="Prize distribution structure")


# ─── Content Agent Schema ───────────────────────────────────────────────────────
class FAQItem(BaseModel):
    question: str
    answer: str


class ContentGTMOutput(BaseModel):
    hero_headline: str
    hero_subheadline: str
    about_copy: str = Field(description="About the hackathon copy (approx 150 words)")
    faq: list[FAQItem] = Field(description="Exactly 8 FAQs with clear answers")
    cta_variants: list[str] = Field(description="Exactly 3 registration call-to-action button text copy variants")
    sponsor_pitch_oneliner: str = Field(description="Sponsor pitch hook sentence")


# ─── Marketing Agent Schema ─────────────────────────────────────────────────────
class TweetItem(BaseModel):
    tweet_num: int
    content: str


class MarketingGTMOutput(BaseModel):
    linkedin_announcement: str = Field(description="Professional post (150-200 words, 5 hashtags)")
    linkedin_countdown: str = Field(description="Urgency/hype tone countdown post (1 week before)")
    whatsapp_announcement: str = Field(description="Casual announcement with emojis (under 100 words)")
    whatsapp_reminder: str = Field(description="Short, punchy WhatsApp reminder (2 days before)")
    instagram_caption: str = Field(description="Trendy, hashtag-heavy caption (10 hashtags)")
    twitter_thread: list[TweetItem] = Field(description="Exactly 3 punchy tweets in a thread")
    hashtags: list[str] = Field(description="Core campaign hashtags list")


# ─── Email Agent Schema ─────────────────────────────────────────────────────────
class EmailGTMOutput(BaseModel):
    invite_subject: str
    invite_body: str = Field(description="Participant invite email body (~300 words)")
    sponsor_subject: str
    sponsor_body: str = Field(description="Sponsor outreach email body (~250 words)")
    confirmation_subject: str
    confirmation_body: str
    reminder_subject: str
    reminder_body: str
    thankyou_subject: str
    thankyou_body: str


# ─── Execution Agent Schema ─────────────────────────────────────────────────────
class WeeklyTaskItem(BaseModel):
    week: str = Field(description="Week index (e.g. 'Week -4', 'Week -1', 'Week +1')")
    tasks: list[str]


class RiskItem(BaseModel):
    risk: str
    mitigation: str


class ExecutionGTMOutput(BaseModel):
    weekly_plan: list[WeeklyTaskItem] = Field(description="Tasks from Week -4 to Week +1")
    day_of_checklist: list[str] = Field(description="Operations checklist for the event day")
    risk_plan: list[RiskItem] = Field(description="5 common risks and their mitigation solutions")
    kpis: list[str] = Field(description="Success metrics to track")
    report_template: str = Field(description="Post-event report markdown template")
